/**
 * Auth Service — Database Schema (Drizzle ORM)
 *
 * This file defines the database tables for the Auth Service.
 * Drizzle reads this file to:
 * 1. Generate SQL migrations (via drizzle-kit)
 * 2. Provide type-safe query building (via drizzle-orm)
 *
 * HOW DRIZZLE WORKS:
 * -----------------
 * You define tables as TypeScript objects using Drizzle's helper functions
 * (pgTable, varchar, boolean, etc.). Drizzle then:
 * - Generates TypeScript types from these definitions (no manual type creation!)
 * - Provides a query builder that knows all your columns and their types
 * - Generates SQL migration files when you run `drizzle-kit generate`
 *
 * So the schema you see below is the SINGLE SOURCE OF TRUTH for:
 * - Database table structure
 * - TypeScript types for database rows
 * - SQL migration files
 */

import {
  boolean,
  index,
  integer,
  pgEnum,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
  varchar,
} from 'drizzle-orm/pg-core';

// ═══ Enums ═══
// PostgreSQL has native enum types — more efficient than varchar with CHECK constraints

export const userRoleEnum = pgEnum('user_role', [
  'CUSTOMER',
  'RIDER',
  'RESTAURANT_OWNER',
  'RESTAURANT_STAFF',
  'ADMIN',
]);

export const accountStatusEnum = pgEnum('account_status', [
  'ACTIVE',
  'SUSPENDED',
  'BANNED',
  'PENDING_VERIFICATION',
]);

export const oauthProviderEnum = pgEnum('oauth_provider', ['GOOGLE', 'APPLE', 'FACEBOOK']);

// ═══ Tables ═══

/**
 * auth_credentials — Core authentication table.
 *
 * Stores login credentials for every user on the platform.
 * One row per user, regardless of whether they're a customer,
 * rider, restaurant owner, or admin.
 */
export const authCredentials = pgTable(
  'auth_credentials',
  {
    /** CUID2 primary key — generated by our application, not the database */
    id: varchar('id', { length: 36 }).primaryKey(),

    /** Email address (nullable — phone-only users don't have email) */
    email: varchar('email', { length: 255 }),

    /** Phone number with country code: "+919876543210" */
    phone: varchar('phone', { length: 20 }),

    /** bcrypt hash of the password (null for OAuth-only users) */
    passwordHash: varchar('password_hash', { length: 255 }),

    /** User's role on the platform */
    role: userRoleEnum('role').notNull(),

    /** Account status */
    status: accountStatusEnum('status').notNull().default('PENDING_VERIFICATION'),

    /** Has the email been verified? */
    emailVerified: boolean('email_verified').notNull().default(false),

    /** Has the phone been verified via OTP? */
    phoneVerified: boolean('phone_verified').notNull().default(false),

    /** Is two-factor authentication enabled? */
    twoFactorEnabled: boolean('two_factor_enabled').notNull().default(false),

    /** Encrypted TOTP secret for 2FA */
    twoFactorSecret: varchar('two_factor_secret', { length: 255 }),

    /** When the user last successfully logged in */
    lastLoginAt: timestamp('last_login_at', { withTimezone: true }),

    /** Consecutive failed login attempts (for account lockout) */
    failedLoginAttempts: integer('failed_login_attempts').notNull().default(0),

    /** Account is locked until this time (null = not locked) */
    lockedUntil: timestamp('locked_until', { withTimezone: true }),

    /** When the record was created */
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),

    /** When the record was last updated */
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    // Partial unique indexes: enforce uniqueness on non-null values only
    // This allows multiple rows with NULL email (phone-only users)
    uniqueIndex('idx_auth_email').on(table.email),
    uniqueIndex('idx_auth_phone').on(table.phone),
    index('idx_auth_role').on(table.role),
    index('idx_auth_status').on(table.status),
  ],
);

/**
 * oauth_accounts — Links users to their OAuth providers.
 *
 * A user can have multiple OAuth accounts (Google + Apple).
 * This table tracks each provider link.
 */
export const oauthAccounts = pgTable(
  'oauth_accounts',
  {
    id: varchar('id', { length: 36 }).primaryKey(),

    /** Links to auth_credentials.id */
    userId: varchar('user_id', { length: 36 })
      .notNull()
      .references(() => authCredentials.id, { onDelete: 'cascade' }),

    /** Which OAuth provider */
    provider: oauthProviderEnum('provider').notNull(),

    /** The user's ID from the OAuth provider */
    providerUserId: varchar('provider_user_id', { length: 255 }).notNull(),

    /** Encrypted OAuth access token */
    accessToken: text('access_token'),

    /** Encrypted OAuth refresh token */
    refreshToken: text('refresh_token'),

    /** When the OAuth token expires */
    tokenExpiresAt: timestamp('token_expires_at', { withTimezone: true }),

    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    // Composite unique: one link per provider per user
    uniqueIndex('idx_oauth_provider_user').on(table.provider, table.providerUserId),
    index('idx_oauth_user').on(table.userId),
  ],
);

/**
 * refresh_tokens — Tracks issued refresh tokens.
 *
 * Why store refresh tokens in the database?
 * - Token revocation: when user logs out, we revoke their token
 * - Token rotation: when a refresh token is used, the old one is revoked
 * - Security: detect token reuse (possible theft) and revoke all tokens
 *
 * We store a HASH of the token, never the plaintext.
 */
export const refreshTokens = pgTable(
  'refresh_tokens',
  {
    id: varchar('id', { length: 36 }).primaryKey(),

    /** Token owner */
    userId: varchar('user_id', { length: 36 })
      .notNull()
      .references(() => authCredentials.id, { onDelete: 'cascade' }),

    /** SHA-256 hash of the refresh token (never store plaintext!) */
    tokenHash: varchar('token_hash', { length: 255 }).notNull(),

    /** User agent or device identifier */
    deviceInfo: varchar('device_info', { length: 500 }),

    /** IP address when the token was created */
    ipAddress: varchar('ip_address', { length: 45 }),

    /** Token expiry time */
    expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),

    /** When the token was revoked (null = still active) */
    revokedAt: timestamp('revoked_at', { withTimezone: true }),

    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    uniqueIndex('idx_refresh_token_hash').on(table.tokenHash),
    index('idx_refresh_user').on(table.userId),
    index('idx_refresh_expires').on(table.expiresAt),
  ],
);

// ═══ Inferred Types ═══
// Drizzle generates TypeScript types from the schema automatically!

/** Type for a row read from auth_credentials */
export type AuthCredential = typeof authCredentials.$inferSelect;

/** Type for inserting a new row into auth_credentials */
export type NewAuthCredential = typeof authCredentials.$inferInsert;

/** Type for a row read from oauth_accounts */
export type OAuthAccount = typeof oauthAccounts.$inferSelect;

/** Type for inserting into oauth_accounts */
export type NewOAuthAccount = typeof oauthAccounts.$inferInsert;

/** Type for a row read from refresh_tokens */
export type RefreshToken = typeof refreshTokens.$inferSelect;

/** Type for inserting into refresh_tokens */
export type NewRefreshToken = typeof refreshTokens.$inferInsert;
